### ISSUE TITLE
Bravado only see first part of the path as a "Resource"

### ISSUE THREAD

**Issue by vavdagic** [Yelp/bravado#338]
Part of my .yaml tree shown bellow
```yaml
basePath: /wp-json
schemes:
  - http
consumes:
  - multipart/form-data
produces:
  - application/json
paths:
  /wp/v2/posts:
    get:
      parameters:
        - name: context
          type: string
```
Why does SwaggerClient only sees "wp" as a Resource? How can i, for instance, get posts?

**Comment by macisamuele** [comment]
In order to call your endpoint the approach is something like
```python
client = ...
response = client.RESOURCE.OPERATION(context="a string).result(timeout=1)
```

* RESOURCE is defined according to the swagger tag associated with the operation or the "first part" of your path ([code reference](https://github.com/Yelp/bravado-core/blob/master/bravado_core/resource.py#L68)). In your case you should have no tags defined so it will be ``wp``
* OPERATION is defined by ``operationId`` attribute if present otherwise by ``<HTTP_VERB>_<PATH_with_no_underscores>`` ([code reference](https://github.com/Yelp/bravado-core/blob/master/bravado_core/operation.py#L13)). In your case you should have ``get_wp_v2_posts``

My suggestion would be to structure a bit more your specs in order to define ``tags`` and ``operationId``s (they are not required fields for Swagger but allows to to have a better experience with tools and to "classify" endpoints)
```yaml
basePath: /wp-json
...
tags:
  - name: my_tag
    description: This tag takes care of a certain area of the API
paths:
  /wp/v2/posts:
    get:
      operationId: get_post_v2
      tags:
        - my_tag
      ...
```
By applying those changes you can access your endpoint as
```python
client.my_tag.get_post_v2(context="a string").result()
```

Closing it for now, feel free to reopen it if this didn't solve your issue
