### ISSUE TITLE
Cannot use boolean query parameter

### ISSUE THREAD

**Issue by frankandrobot** [Yelp/bravado#380]
An endpoint is programmed to accept a boolean as an query parameter:

```yaml
      - in: query
        name: asc_order
        type: boolean
        default: true
```

Unfortunately, under the hood, we're using a JSON parser to parse query parameters. That means that because bravado sends "F" and "T" that I am unable to set this parameter; otherwise I get a 400: 

```
HTTPBadRequest: 400 Bad Request: APIError(code=25, error=u"The parameter asc_order cannot be deserialized: invalid character 'F' looking for beginning of value", payload=None)
```

How do I send a `true`/`false` instead?
